version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/src/main/resources/archetype-resources"
    schedule:
      interval: "weekly"
    labels:
      - "maven"
      - "dependencies"
    reviewers:
      - "rhacs"
